package com.insurancemantra.entity;
// Generated Dec 3, 2016 12:09:10 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PolicySubCategory generated by hbm2java
 */
public class PolicySubCategory implements java.io.Serializable {

	private Integer subCategoryId;
	private PolicyCategory policyCategory;
	private String subCategoryName;
	private Date creationDate;
	private String subCategoryDesc;
	private String subCategoryFeatures;
	private String subCategoryBenefits;
	private Set<PolicyPlan> policyPlans = new HashSet<PolicyPlan>(0);

	public PolicySubCategory() {
	}

	public PolicySubCategory(PolicyCategory policyCategory, String subCategoryName) {
		this.policyCategory = policyCategory;
		this.subCategoryName = subCategoryName;
	}

	public PolicySubCategory(PolicyCategory policyCategory, String subCategoryName, Date creationDate,
			String subCategoryDesc, String subCategoryFeatures, String subCategoryBenefits,
			Set<PolicyPlan> policyPlans) {
		this.policyCategory = policyCategory;
		this.subCategoryName = subCategoryName;
		this.creationDate = creationDate;
		this.subCategoryDesc = subCategoryDesc;
		this.subCategoryFeatures = subCategoryFeatures;
		this.subCategoryBenefits = subCategoryBenefits;
		this.policyPlans = policyPlans;
	}

	public Integer getSubCategoryId() {
		return this.subCategoryId;
	}

	public void setSubCategoryId(Integer subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public PolicyCategory getPolicyCategory() {
		return this.policyCategory;
	}

	public void setPolicyCategory(PolicyCategory policyCategory) {
		this.policyCategory = policyCategory;
	}

	public String getSubCategoryName() {
		return this.subCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getSubCategoryDesc() {
		return this.subCategoryDesc;
	}

	public void setSubCategoryDesc(String subCategoryDesc) {
		this.subCategoryDesc = subCategoryDesc;
	}

	public String getSubCategoryFeatures() {
		return this.subCategoryFeatures;
	}

	public void setSubCategoryFeatures(String subCategoryFeatures) {
		this.subCategoryFeatures = subCategoryFeatures;
	}

	public String getSubCategoryBenefits() {
		return this.subCategoryBenefits;
	}

	public void setSubCategoryBenefits(String subCategoryBenefits) {
		this.subCategoryBenefits = subCategoryBenefits;
	}

	public Set<PolicyPlan> getPolicyPlans() {
		return this.policyPlans;
	}

	public void setPolicyPlans(Set<PolicyPlan> policyPlans) {
		this.policyPlans = policyPlans;
	}

}
