package com.insurancemantra.entity;
// Generated Dec 3, 2016 12:09:10 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * PolicyOrderHistory generated by hbm2java
 */
public class PolicyOrderHistory implements java.io.Serializable {

	private Long orderId;
	private PolicyBrand policyBrand;
	private PolicyPlan policyPlan;
	private PolicyUser policyUser;
	private String requesterName;
	private String requesterEmail;
	private int requesterPhone;
	private Date requesterDob;
	private String requesterIncome;
	private String orderStatus;
	private Date orderCreationDate;
	private Date orderCompletionDate;

	public PolicyOrderHistory() {
	}

	public PolicyOrderHistory(PolicyBrand policyBrand, PolicyPlan policyPlan, PolicyUser policyUser,
			String requesterName, int requesterPhone) {
		this.policyBrand = policyBrand;
		this.policyPlan = policyPlan;
		this.policyUser = policyUser;
		this.requesterName = requesterName;
		this.requesterPhone = requesterPhone;
	}

	public PolicyOrderHistory(PolicyBrand policyBrand, PolicyPlan policyPlan, PolicyUser policyUser,
			String requesterName, String requesterEmail, int requesterPhone, Date requesterDob, String requesterIncome,
			String orderStatus, Date orderCreationDate, Date orderCompletionDate) {
		this.policyBrand = policyBrand;
		this.policyPlan = policyPlan;
		this.policyUser = policyUser;
		this.requesterName = requesterName;
		this.requesterEmail = requesterEmail;
		this.requesterPhone = requesterPhone;
		this.requesterDob = requesterDob;
		this.requesterIncome = requesterIncome;
		this.orderStatus = orderStatus;
		this.orderCreationDate = orderCreationDate;
		this.orderCompletionDate = orderCompletionDate;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public PolicyBrand getPolicyBrand() {
		return this.policyBrand;
	}

	public void setPolicyBrand(PolicyBrand policyBrand) {
		this.policyBrand = policyBrand;
	}

	public PolicyPlan getPolicyPlan() {
		return this.policyPlan;
	}

	public void setPolicyPlan(PolicyPlan policyPlan) {
		this.policyPlan = policyPlan;
	}

	public PolicyUser getPolicyUser() {
		return this.policyUser;
	}

	public void setPolicyUser(PolicyUser policyUser) {
		this.policyUser = policyUser;
	}

	public String getRequesterName() {
		return this.requesterName;
	}

	public void setRequesterName(String requesterName) {
		this.requesterName = requesterName;
	}

	public String getRequesterEmail() {
		return this.requesterEmail;
	}

	public void setRequesterEmail(String requesterEmail) {
		this.requesterEmail = requesterEmail;
	}

	public int getRequesterPhone() {
		return this.requesterPhone;
	}

	public void setRequesterPhone(int requesterPhone) {
		this.requesterPhone = requesterPhone;
	}

	public Date getRequesterDob() {
		return this.requesterDob;
	}

	public void setRequesterDob(Date requesterDob) {
		this.requesterDob = requesterDob;
	}

	public String getRequesterIncome() {
		return this.requesterIncome;
	}

	public void setRequesterIncome(String requesterIncome) {
		this.requesterIncome = requesterIncome;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getOrderCreationDate() {
		return this.orderCreationDate;
	}

	public void setOrderCreationDate(Date orderCreationDate) {
		this.orderCreationDate = orderCreationDate;
	}

	public Date getOrderCompletionDate() {
		return this.orderCompletionDate;
	}

	public void setOrderCompletionDate(Date orderCompletionDate) {
		this.orderCompletionDate = orderCompletionDate;
	}

}
