package com.insurancemantra.entity;
// Generated Dec 3, 2016 12:09:10 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PolicyPlan generated by hbm2java
 */
public class PolicyPlan implements java.io.Serializable {

	private Integer planId;
	private PolicyBrand policyBrand;
	private PolicySubCategory policySubCategory;
	private String planName;
	private String minEntryAge;
	private String maxEntryAge;
	private String planMaturity;
	private String premiumAmount;
	private String sumAssured;
	private String planDesc;
	private String planFeatures;
	private Date creationDate;
	private Set<PolicyOrderHistory> policyOrderHistories = new HashSet<PolicyOrderHistory>(0);

	public PolicyPlan() {
	}

	public PolicyPlan(PolicyBrand policyBrand, PolicySubCategory policySubCategory, String planName, String minEntryAge,
			String maxEntryAge) {
		this.policyBrand = policyBrand;
		this.policySubCategory = policySubCategory;
		this.planName = planName;
		this.minEntryAge = minEntryAge;
		this.maxEntryAge = maxEntryAge;
	}

	public PolicyPlan(PolicyBrand policyBrand, PolicySubCategory policySubCategory, String planName, String minEntryAge,
			String maxEntryAge, String planMaturity, String premiumAmount, String sumAssured, String planDesc,
			String planFeatures, Date creationDate, Set<PolicyOrderHistory> policyOrderHistories) {
		this.policyBrand = policyBrand;
		this.policySubCategory = policySubCategory;
		this.planName = planName;
		this.minEntryAge = minEntryAge;
		this.maxEntryAge = maxEntryAge;
		this.planMaturity = planMaturity;
		this.premiumAmount = premiumAmount;
		this.sumAssured = sumAssured;
		this.planDesc = planDesc;
		this.planFeatures = planFeatures;
		this.creationDate = creationDate;
		this.policyOrderHistories = policyOrderHistories;
	}

	public Integer getPlanId() {
		return this.planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	public PolicyBrand getPolicyBrand() {
		return this.policyBrand;
	}

	public void setPolicyBrand(PolicyBrand policyBrand) {
		this.policyBrand = policyBrand;
	}

	public PolicySubCategory getPolicySubCategory() {
		return this.policySubCategory;
	}

	public void setPolicySubCategory(PolicySubCategory policySubCategory) {
		this.policySubCategory = policySubCategory;
	}

	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	public String getMinEntryAge() {
		return this.minEntryAge;
	}

	public void setMinEntryAge(String minEntryAge) {
		this.minEntryAge = minEntryAge;
	}

	public String getMaxEntryAge() {
		return this.maxEntryAge;
	}

	public void setMaxEntryAge(String maxEntryAge) {
		this.maxEntryAge = maxEntryAge;
	}

	public String getPlanMaturity() {
		return this.planMaturity;
	}

	public void setPlanMaturity(String planMaturity) {
		this.planMaturity = planMaturity;
	}

	public String getPremiumAmount() {
		return this.premiumAmount;
	}

	public void setPremiumAmount(String premiumAmount) {
		this.premiumAmount = premiumAmount;
	}

	public String getSumAssured() {
		return this.sumAssured;
	}

	public void setSumAssured(String sumAssured) {
		this.sumAssured = sumAssured;
	}

	public String getPlanDesc() {
		return this.planDesc;
	}

	public void setPlanDesc(String planDesc) {
		this.planDesc = planDesc;
	}

	public String getPlanFeatures() {
		return this.planFeatures;
	}

	public void setPlanFeatures(String planFeatures) {
		this.planFeatures = planFeatures;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Set<PolicyOrderHistory> getPolicyOrderHistories() {
		return this.policyOrderHistories;
	}

	public void setPolicyOrderHistories(Set<PolicyOrderHistory> policyOrderHistories) {
		this.policyOrderHistories = policyOrderHistories;
	}

}
