package com.insurancemantra.entity;
// Generated Dec 3, 2016 12:09:10 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PolicyCategory generated by hbm2java
 */
public class PolicyCategory implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private Date creationDate;
	private String categoryDesc;
	private Set<PolicySubCategory> policySubCategories = new HashSet<PolicySubCategory>(0);

	public PolicyCategory() {
	}

	public PolicyCategory(String categoryName) {
		this.categoryName = categoryName;
	}

	public PolicyCategory(String categoryName, Date creationDate, String categoryDesc,
			Set<PolicySubCategory> policySubCategories) {
		this.categoryName = categoryName;
		this.creationDate = creationDate;
		this.categoryDesc = categoryDesc;
		this.policySubCategories = policySubCategories;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public Set<PolicySubCategory> getPolicySubCategories() {
		return this.policySubCategories;
	}

	public void setPolicySubCategories(Set<PolicySubCategory> policySubCategories) {
		this.policySubCategories = policySubCategories;
	}

}
