package com.insurancemantra.entity;
// Generated Dec 3, 2016 12:09:10 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PolicyBrand generated by hbm2java
 */
public class PolicyBrand implements java.io.Serializable {

	private Integer brandId;
	private String brandName;
	private Date creationDate;
	private String brandEmail;
	private String password;
	private String brandAddress;
	private String brandCity;
	private String brandState;
	private String brandCountry;
	private Integer brandPhone;
	private String brandStatus;
	private Set<PolicyOrderHistory> policyOrderHistories = new HashSet<PolicyOrderHistory>(0);
	private Set<PolicyPlan> policyPlans = new HashSet<PolicyPlan>(0);

	public PolicyBrand() {
	}

	public PolicyBrand(String brandName, String password) {
		this.brandName = brandName;
		this.password = password;
	}

	public PolicyBrand(String brandName, Date creationDate, String brandEmail, String password, String brandAddress,
			String brandCity, String brandState, String brandCountry, Integer brandPhone, String brandStatus,
			Set<PolicyOrderHistory> policyOrderHistories, Set<PolicyPlan> policyPlans) {
		this.brandName = brandName;
		this.creationDate = creationDate;
		this.brandEmail = brandEmail;
		this.password = password;
		this.brandAddress = brandAddress;
		this.brandCity = brandCity;
		this.brandState = brandState;
		this.brandCountry = brandCountry;
		this.brandPhone = brandPhone;
		this.brandStatus = brandStatus;
		this.policyOrderHistories = policyOrderHistories;
		this.policyPlans = policyPlans;
	}

	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getBrandEmail() {
		return this.brandEmail;
	}

	public void setBrandEmail(String brandEmail) {
		this.brandEmail = brandEmail;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getBrandAddress() {
		return this.brandAddress;
	}

	public void setBrandAddress(String brandAddress) {
		this.brandAddress = brandAddress;
	}

	public String getBrandCity() {
		return this.brandCity;
	}

	public void setBrandCity(String brandCity) {
		this.brandCity = brandCity;
	}

	public String getBrandState() {
		return this.brandState;
	}

	public void setBrandState(String brandState) {
		this.brandState = brandState;
	}

	public String getBrandCountry() {
		return this.brandCountry;
	}

	public void setBrandCountry(String brandCountry) {
		this.brandCountry = brandCountry;
	}

	public Integer getBrandPhone() {
		return this.brandPhone;
	}

	public void setBrandPhone(Integer brandPhone) {
		this.brandPhone = brandPhone;
	}

	public String getBrandStatus() {
		return this.brandStatus;
	}

	public void setBrandStatus(String brandStatus) {
		this.brandStatus = brandStatus;
	}

	public Set<PolicyOrderHistory> getPolicyOrderHistories() {
		return this.policyOrderHistories;
	}

	public void setPolicyOrderHistories(Set<PolicyOrderHistory> policyOrderHistories) {
		this.policyOrderHistories = policyOrderHistories;
	}

	public Set<PolicyPlan> getPolicyPlans() {
		return this.policyPlans;
	}

	public void setPolicyPlans(Set<PolicyPlan> policyPlans) {
		this.policyPlans = policyPlans;
	}

}
