package com.insurancemantra.entity;
// Generated Dec 3, 2016 12:09:10 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PolicyUser generated by hbm2java
 */
public class PolicyUser implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String password;
	private String userEmail;
	private String userRole;
	private Date userDob;
	private String userAddress;
	private String userCity;
	private String userState;
	private String userCountry;
	private Integer userPhone;
	private Date creationDate;
	private String name;
	private Set<PolicyOrderHistory> policyOrderHistories = new HashSet<PolicyOrderHistory>(0);

	public PolicyUser() {
	}

	public PolicyUser(String userName, String password, String name) {
		this.userName = userName;
		this.password = password;
		this.name = name;
	}

	public PolicyUser(String userName, String password, String userEmail, String userRole, Date userDob,
			String userAddress, String userCity, String userState, String userCountry, Integer userPhone,
			Date creationDate, String name, Set<PolicyOrderHistory> policyOrderHistories) {
		this.userName = userName;
		this.password = password;
		this.userEmail = userEmail;
		this.userRole = userRole;
		this.userDob = userDob;
		this.userAddress = userAddress;
		this.userCity = userCity;
		this.userState = userState;
		this.userCountry = userCountry;
		this.userPhone = userPhone;
		this.creationDate = creationDate;
		this.name = name;
		this.policyOrderHistories = policyOrderHistories;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public Date getUserDob() {
		return this.userDob;
	}

	public void setUserDob(Date userDob) {
		this.userDob = userDob;
	}

	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserCity() {
		return this.userCity;
	}

	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

	public String getUserCountry() {
		return this.userCountry;
	}

	public void setUserCountry(String userCountry) {
		this.userCountry = userCountry;
	}

	public Integer getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(Integer userPhone) {
		this.userPhone = userPhone;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<PolicyOrderHistory> getPolicyOrderHistories() {
		return this.policyOrderHistories;
	}

	public void setPolicyOrderHistories(Set<PolicyOrderHistory> policyOrderHistories) {
		this.policyOrderHistories = policyOrderHistories;
	}

}
